[package]
name = "libgarble"
version = "0.1.0"
authors = ["aweinstock"]

[lib]
name="garble"
crate-type=["staticlib", "dylib"]

[dependencies]
libc = "0.2.15"
openssl-sys = "0.7.17"
simd = { git = "https://github.com/huonw/simd" }
